###########################################################################

#

# 配置数据源相关，使用阿里巴巴的druid数据源

#

###########################################################################



spring:

  datasource:

    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://localhost:3306/shortvideo?characterEncoding=UTF-8

    username: root

    password: 123456

    druid:

      initial-size: 1

      min-idle: 1

      max-active: 20

      test-on-borrow: true

      stat-view-servlet:

        allow: true



  #文件上传配置

  servlet:

    multipart:

      max-file-size: 100Mb

      max-request-size: 1000Mb



  #关闭缓存，即时刷新

  thymeleaf:

    cache: true



  #热部署生效

  devtools:

    restart:

      enabled: true

      #设置重启的目录，添加哪个目录的文件需要restart

      additional-paths: src/main/java

      #排除哪个目录文件不需要restart，资源文件修改建议手动重启

      #也可以设置WEB-INF文件夹内容修改不重启exclude: WEB-INF/**

      #exclude: static/**,public/**



  ###########################################################################

  #

  #REDIS配置

  #

  ###########################################################################

  redis:

    #Redis数据库索引（默认为0）

    database: 1

    #Redis服务器地址

    host: 192.168.67.129

    #Redis服务器连接端口

    port: 6379

    #Redis服务器连接密码（默认为空）

    password: immoc



    jedis:

      pool:

        #连接池最大连接数（使用负值表示没有限制）

        max-active: 1000

        #连接池最大阻塞等待时间（使用负值表示没有限制）

        max-wait: -1ms

        #连接池最大空闲连接

        max-idle: 10

        #连接池最小空闲连接

        min-idle: 2

    #连接超时时间（毫秒）注意：不能设置为0不然会报错

    timeout: 2000ms





###########################################################################

#

# mybatis 配置

#

###########################################################################

mybatis:

  type-aliases-package: com.yuhangTao.pojo # pojo工程下的pojo包

  mapper-locations: classpath:mapper/*.xml



#通用Mapper配置

mapper:

  mappers: com.yuhangTao.utils.MyMapper

  not-empty: false

  identity: MYSQL



#分页插件配置

pagehelper:

  helper-dialect: mysql

  #  reasonable: true

  support-methods-arguments: true

  params: count=countSql



###########################################################################

#

#基本设置

#

###########################################################################

#配置api端口号

server:

  port: 8081

  servlet:

    context-path: /short_video

  #tomcat的URI编码

  tomcat:

    uri-encoding: UTF-8